[package]
name = "cargo-hack"
version = "0.3.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/cargo-hack"
homepage = "https://github.com/taiki-e/cargo-hack"
keywords = ["cargo", "subcommand"]
categories = ["command-line-utilities", "development-tools::cargo-plugins", "development-tools::build-utils"]
readme = "README.md"
description = """
A tool to work around some limitations on cargo.
"""

[workspace]

[dependencies]
anyhow = "1.0.19"
# serde = { version = "1.0.102", features = ["derive"] }
serde = "1.0.102"
serde_derive = "1.0.102"
serde_json = "1.0.41"
termcolor = "1.0.5"
toml = "0.5.5"

[dev-dependencies]
easy-ext = "0.1.6"
